@extends('layouts.admin') @section('title',$producto->exists?'Editar producto':'Nuevo producto') @section('content')
<div class="head"><div><h1>{{ $producto->exists?'Editar producto':'Nuevo producto' }}</h1><p>Los cambios quedan disponibles para el chatbot inmediatamente.</p></div></div>
<form class="card" method="POST" enctype="multipart/form-data" action="{{ $producto->exists?route('productos.update',$producto):route('productos.store') }}">@csrf @if($producto->exists)@method('PUT')@endif<div class="grid">
@foreach(['codigo'=>'Código','nombre'=>'Nombre','categoria'=>'Categoría','unidad_medida'=>'Unidad de medida','precio'=>'Precio','stock'=>'Stock'] as $name=>$label)<div><label>{{ $label }}</label><input name="{{ $name }}" type="{{ in_array($name,['precio','stock'])?'number':'text' }}" @if($name==='precio')step="0.01"@endif value="{{ old($name,$producto->{$name}??($name==='unidad_medida'?'unidad':'')) }}" required>@error($name)<div class="error">{{ $message }}</div>@enderror</div>@endforeach
<div class="full"><label>Descripción</label><textarea name="descripcion">{{ old('descripcion',$producto->descripcion) }}</textarea></div>
<div class="full"><label>URL externa de imagen (opcional)</label><input type="url" name="imagen_url" value="{{ old('imagen_url',str_starts_with($producto->imagen_url??'','http')?$producto->imagen_url:'') }}" placeholder="https://..."></div>
<div><label>Subir imagen del producto</label><input name="image_file" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><small>JPG, PNG, WEBP o GIF, máximo 4 MB.</small>@error('image_file')<div class="error">{{ $message }}</div>@enderror</div>
<div><label>Ficha o catálogo PDF</label><input name="document_file" type="file" accept="application/pdf"><small>@if($producto->document_name)Actual: {{ $producto->document_name }}@else Máximo 10 MB.@endif</small>@error('document_file')<div class="error">{{ $message }}</div>@enderror</div>
<div class="full check"><input type="hidden" name="activo" value="0"><input id="activo" name="activo" type="checkbox" value="1" @checked(old('activo',$producto->exists?$producto->activo:true))><label for="activo">Producto activo y visible para el chatbot</label></div></div>
<div class="actions"><a class="btn light" href="{{ route('productos.index') }}">Cancelar</a><button class="btn">Guardar producto</button></div></form>@endsection
