<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administrar catálogo · ChatBoalar</title>
<style>:root{--green:#159765;--dark:#10271f;--line:#e1e9e5;--muted:#6d7b75;--bg:#f4f7f5}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#17231e;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.top{background:var(--dark);color:#fff;padding:18px 0}.wrap{width:min(1180px,calc(100% - 32px));margin:auto}.top .wrap{display:flex;align-items:center;justify-content:space-between}.brand{font-size:19px;font-weight:800}.brand span{color:#43d99b}.back{color:#c8d9d2;text-decoration:none;font-size:13px}.content{padding:30px 0}.heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.heading h1{font-size:25px;margin:0 0 4px}.heading p{color:var(--muted);margin:0;font-size:13px}.btn{display:inline-block;border:0;border-radius:9px;background:var(--green);color:#fff;text-decoration:none;padding:10px 14px;font-size:13px;font-weight:750;cursor:pointer}.btn.gray{background:#eef2f0;color:#293830}.btn.red{background:#fff0ee;color:#c54436}.alert{padding:13px 16px;border-radius:10px;margin-bottom:15px;background:#e7f8f0;color:#087447;font-size:13px}.alert.warn{background:#fff4df;color:#956006}.panel{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden;box-shadow:0 10px 30px rgba(20,40,30,.06)}.tools{padding:15px;display:flex;gap:10px;border-bottom:1px solid var(--line)}input[type=search]{width:min(420px,100%);padding:10px 12px;border:1px solid #ccd8d2;border-radius:9px;font:inherit}table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;padding:12px 14px;color:var(--muted);font-size:10px;letter-spacing:.6px;text-transform:uppercase}td{padding:13px 14px;border-top:1px solid var(--line)}.product{display:flex;gap:11px;align-items:center}.pic{width:42px;height:42px;border-radius:10px;background:#ecf8f2;object-fit:cover;display:grid;place-items:center}.product b,.product small{display:block}.product small{color:var(--muted);margin-top:2px}.pill{padding:5px 9px;background:#ecf8f2;color:#087447;border-radius:20px;font-size:11px;font-weight:700}.pill.off{background:#f0f1f1;color:#707975}.actions{display:flex;gap:6px;align-items:center}.actions form{margin:0}.pagination{padding:16px;color:var(--muted);font-size:12px}.empty{text-align:center;padding:40px;color:var(--muted)}@media(max-width:800px){th:nth-child(2),td:nth-child(2),th:nth-child(4),td:nth-child(4){display:none}.heading{align-items:flex-start}.wrap{width:min(100% - 20px,1180px)}.actions{flex-direction:column;align-items:stretch}}</style></head><body>
<header class="top"><div class="wrap"><div class="brand"><span>✦</span> ChatBoalar</div><a class="back" href="{{ url('/') }}">← Volver al panel</a></div></header>
<main class="wrap content"><div class="heading"><div><h1>Catálogo de productos</h1><p>Crea, modifica, activa y elimina productos del chatbot.</p></div><a class="btn" href="{{ route('productos.create') }}">+ Nuevo producto</a></div>
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif @if(session('warning'))<div class="alert warn">{{ session('warning') }}</div>@endif
<section class="panel"><form class="tools" method="GET"><input type="search" name="buscar" value="{{ request('buscar') }}" placeholder="Buscar por nombre, código o categoría"><button class="btn gray">Buscar</button>@if(request('buscar'))<a class="btn gray" href="{{ route('productos.index') }}">Limpiar</a>@endif</form>
<table><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@forelse($productos as $producto)<tr><td><div class="product">@if($producto->imagen_url)<img class="pic" src="{{ $producto->imagen_url }}" alt="">@else<span class="pic">◇</span>@endif<div><b>{{ $producto->nombre }}</b><small>{{ $producto->codigo }} · {{ $producto->unidad_medida }}</small></div></div></td><td>{{ ucfirst($producto->categoria) }}</td><td>${{ number_format((float)$producto->precio,2,',','.') }}</td><td>{{ $producto->stock }}</td><td><span class="pill {{ $producto->activo ? '' : 'off' }}">{{ $producto->activo ? 'Activo' : 'Inactivo' }}</span></td><td><div class="actions"><a class="btn gray" href="{{ route('productos.edit',$producto) }}">Editar</a><form method="POST" action="{{ route('productos.destroy',$producto) }}" onsubmit="return confirm('¿Eliminar este producto?')">@csrf @method('DELETE')<button class="btn red">Eliminar</button></form></div></td></tr>
@empty<tr><td colspan="6" class="empty">No se encontraron productos.</td></tr>@endforelse</tbody></table><div class="pagination">Mostrando {{ $productos->firstItem() ?? 0 }}–{{ $productos->lastItem() ?? 0 }} de {{ $productos->total() }} productos</div></section></main></body></html>
