@extends('layouts.admin') @section('title','Integraciones') @section('content')
<div class="head"><div><h1>Integraciones</h1><p>Configura los servicios sin editar código. Las claves se almacenan cifradas.</p></div></div>
<div style="display:grid;gap:18px">
<section class="card" style="border:2px solid var(--p)"><div class="head" style="margin:0 0 18px"><div><h2 style="margin:0;font-size:18px">Canal principal de WhatsApp</h2><p>Elige por dónde se recibirán y enviarán los mensajes del chatbot.</p></div><span class="pill {{ $canalPrincipal==='ninguno'?'off':'' }}">{{ $canalPrincipal==='evolution'?'EVOLUTION API':($canalPrincipal==='whatsapp'?'WHATSAPP CLOUD':'SIN CANAL') }}</span></div><form method="POST" action="{{ route('integraciones.channel') }}">@csrf @method('PUT')<div class="grid"><div class="full"><label for="channel">Proveedor que utilizará el sistema</label><select id="channel" name="channel" required><option value="evolution" @selected($canalPrincipal==='evolution')>Evolution API · EasyPanel (recomendado)</option><option value="whatsapp" @selected($canalPrincipal==='whatsapp')>WhatsApp Cloud API · Meta</option><option value="ninguno" @selected($canalPrincipal==='ninguno')>Desactivar WhatsApp temporalmente</option></select>@error('channel')<div class="error">{{ $message }}</div>@enderror<small>Solo un proveedor puede estar activo a la vez. Cambiar esta opción no borra sus credenciales.</small></div></div><div class="actions"><button class="btn">Aplicar canal principal</button></div></form></section>
@php($cards=[['id'=>'whatsapp','title'=>'WhatsApp Cloud API','desc'=>'Conexión oficial de Meta','item'=>$whatsapp],['id'=>'evolution','title'=>'Evolution API · EasyPanel','desc'=>'Instancia conectada mediante QR o Cloud API','item'=>$evolution],['id'=>'openai','title'=>'OpenAI','desc'=>'Inteligencia artificial del chatbot','item'=>$openai]])
@foreach($cards as $card)<section class="card"><div class="head" style="margin:0 0 18px"><div><h2 style="margin:0;font-size:17px">{{ $card['title'] }}</h2><p>{{ $card['desc'] }}</p></div><span class="pill {{ $card['item']->configured()?'':'off' }}">{{ $card['item']->configured()?'ACTIVO':'PENDIENTE' }}</span></div>
<form method="POST" action="{{ route('integraciones.update',$card['id']) }}">@csrf @method('PUT')<div class="grid">
@if($card['id']==='whatsapp')
<div class="full"><label>Token de acceso permanente</label><input type="password" name="access_token" placeholder="{{ filled($whatsapp->access_token)?'•••••••• (guardado)':'Token de Meta' }}"></div><div><label>Phone Number ID</label><input name="phone_number_id" value="{{ data_get($whatsapp->settings,'phone_number_id') }}" required></div><div><label>Versión API</label><input name="api_version" value="{{ data_get($whatsapp->settings,'api_version','v23.0') }}" required></div><div><label>Token de verificación</label><input name="verify_token" value="{{ data_get($whatsapp->settings,'verify_token') }}" required></div><div><label>App Secret</label><input type="password" name="app_secret" placeholder="{{ filled($whatsapp->secret)?'•••••••• (guardado)':'App Secret' }}"></div>
@elseif($card['id']==='evolution')
<div class="full"><label>URL pública de Evolution API</label><input type="url" name="base_url" value="{{ data_get($evolution->settings,'base_url') }}" placeholder="https://evolution.tudominio.com" required></div><div><label>Nombre de la instancia</label><input name="instance" value="{{ data_get($evolution->settings,'instance') }}" placeholder="limpieza-total" required></div><div><label>API Key</label><input type="password" name="access_token" placeholder="{{ filled($evolution->access_token)?'•••••••• (guardada)':'API key de Evolution' }}"></div><div class="full" style="padding:12px;background:#f3f7f5;border-radius:9px"><strong>Webhook de mensajes:</strong><br><code>{{ url('/api/evolution/webhook') }}</code><br><small>En Evolution activa Enabled y el evento MESSAGES_UPSERT. Deja Webhook by Events y Webhook Base64 desactivados.</small></div>
@else
<div class="full"><label>API Key</label><input type="password" name="access_token" placeholder="{{ filled($openai->access_token)?'•••••••• (guardada)':'sk-...' }}"></div><div><label>Modelo</label><input name="model" value="{{ data_get($openai->settings,'model','gpt-5.6-sol') }}" required></div><div><label>Máximo de tokens</label><input type="number" name="max_tokens" value="{{ data_get($openai->settings,'max_tokens',500) }}" min="50" max="16000" required></div><div><label>Temperatura</label><input type="number" step="0.1" name="temperature" value="{{ data_get($openai->settings,'temperature',0.7) }}" min="0" max="2" required></div>
@endif
@if($card['id']==='openai')<div class="full check"><input type="hidden" name="enabled" value="0"><input id="enabled-openai" type="checkbox" name="enabled" value="1" @checked($card['item']->enabled)><label for="enabled-openai">Usar OpenAI en el chatbot</label></div>@else<div class="full"><span class="pill {{ $card['item']->enabled?'':'off' }}">{{ $card['item']->enabled?'CANAL SELECCIONADO':'NO SELECCIONADO' }}</span></div>@endif</div><div class="actions"><button class="btn">Guardar {{ $card['title'] }}</button></div></form>
<form method="POST" action="{{ route('integraciones.test',$card['id']) }}" style="text-align:right;margin-top:9px">@csrf<button class="btn light">Probar conexión</button></form></section>@endforeach
<section class="card"><div class="head" style="margin:0"><div><h2 style="margin:0;font-size:17px">MySQL</h2><p>{{ $mysql['database']??'Base no disponible' }} · {{ $mysql['host'] }}</p></div><span class="pill {{ $mysql['success']?'':'off' }}">{{ $mysql['success']?'ACTIVO':'ERROR' }}</span></div><form method="POST" action="{{ route('integraciones.test','mysql') }}" class="actions">@csrf<button class="btn light">Comprobar MySQL</button></form></section>
</div>@endsection
